name: Claude Code

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude-code:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'claude')) ||
      (github.event_name == 'issue_comment' && contains(github.event.issue.labels.*.name, 'claude'))
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Set up Claude Code
        run: |
          npm install -g @anthropic-ai/claude-code
          
      - name: Configure git
        run: |
          git config --global user.name "Claude Code Bot"
          git config --global user.email "claude-code@example.com"
          
      - name: Run Claude Code
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract issue content
          if [ "${{ github.event_name }}" = "issues" ]; then
            PROMPT="${{ github.event.issue.body }}"
          else
            PROMPT="${{ github.event.comment.body }}"
          fi
          
          # Run Claude Code with file creation options
          echo "$PROMPT" | claude --non-interactive --write-files --commit-changes
          
      - name: Check for changes
        id: check_changes
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Claude Code: ${{ github.event.issue.title }}"
          title: "Claude Code: ${{ github.event.issue.title }}"
          body: |
            This PR was automatically generated by Claude Code based on issue #${{ github.event.issue.number }}.
            
            Original request:
            ${{ github.event.issue.body }}
          branch: claude-code-${{ github.event.issue.number }}
          labels: |
            automated
            claude-code
